Update signature on various count() methods
Each produced a fatal when running `make phpunit`.  Ex:

    Fatal error: During inheritance of Countable: Uncaught Return type
    of CirrusSearch\Maintenance\Set::count() should either be compatible
    with Countable::count(): int, or the #[\ReturnTypeWillChange]
    attribute should be used to temporarily suppress the notice

Bug: T289879
Change-Id: I34aff7d06290064e3e855ef9f2babc6afaa93d44
(cherry picked from commit 1345ffc250e62a720e8576cb02a2ac3d2c8c8cc1)