Defer SearchConfig instantiation when it's actually needed
I think something changed in maint scripts, SearchConfig was
instantiated in Maintenance::finalSetup() and copied in
to the new maint script in runChild.
I suppose it's not working anymore (still unclear to me) and
searchConfig remains null when a cirrus maint script is called
via runChild from a non cirrus maint script.
Another problem is related to wfLoadExtension, apparently MediaWikiServices
is not fully configured when finalSetup() is called resulting in:

Fatal error: Uncaught exception 'ConfigException' with message 'No registered builder available for CirrusSearch.' in /vagrant/mediawiki/includes/config/ConfigFactory.php on line 131

Switching to getter that will lazy load SearchConfig seems to fix
the issue.

Bug: T142153
Bug: T142652
Change-Id: I7f0108c350215eea545170915e7d5abb85f33ad2