Improve error logging for script errors
The root_cause field of ElasticSearch error responses is kinda
useless, as it does not include recursive causes (caused_by field
within another caused_by field). Also, script errors include a
stack trace for the script, which by default would not be included
in the message.

Example error before the patch:

    script_exception: link error

Example error message after the patch:

    script_exception: link error (Fielddata is disabled on text
    fields by default. Set fielddata=true on [outgoing_link] in
    order to load fielddata in memory by uninverting the inverted
    index. Note that this can however use significant memory.
    Alternatively use a keyword field instead.)
        doc['outgoing_link'].length
        ^---- HERE

Change-Id: I47d03b410bff0abaa15643eb6facb54d0f5e50a5